<?xml version='1.0'?>

<!--

Copyright 2019 Double Precision, Inc.
See COPYING for distribution information.

Stylesheet for creating #includes of headers for appearance objects that are
defined in appearance/*.xml

-->

<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">

  <xsl:output method="text" />

  <xsl:template match="/root">
    <xsl:text>/* Automatically generated by appearance_create_proto.xsl */
</xsl:text>

    <xsl:for-each select="appearance">
      <xsl:call-template name="appearance" />
    </xsl:for-each>

  </xsl:template>

  <xsl:template name="appearance">
    <xsl:text>//! Appearance generator&#10;&#10;void generate(const generate_info &amp;, const </xsl:text>
    <xsl:value-of select="name" />
    <xsl:text>_appearance &amp;appearance);&#10;&#10;//! Appearance generator&#10;const_</xsl:text>
    <xsl:value-of select="name"/>
    <xsl:text>_appearance generate(const theme_parser_lock &amp;,
    const const_</xsl:text>
    <xsl:value-of select="name"/>
    <xsl:text>_appearance &amp;);
//! Appearance generator&#10;&#10;const_</xsl:text>
    <xsl:value-of select="name"/>
    <xsl:text>_appearance do_generate(const theme_parser_lock &amp;,
    const const_</xsl:text>
    <xsl:value-of select="name"/>
    <xsl:text>_appearance &amp;);&#10;</xsl:text>
  </xsl:template>
</xsl:stylesheet>
