/*
** Copyright 2021 Double Precision, Inc.
** See COPYING for distribution information.
*/
#ifndef x_w_screen_positions_confighandle_h
#define x_w_screen_positions_confighandle_h

#include <x/w/impl/screen_positions_confighandlefwd.H>
#include <x/w/impl/screen_positions_confighandleobj.H>
#include <x/w/screen_positions.H>
#include <x/xml/writelock.H>
#include <x/xml/readlock.H>

LIBCXXW_NAMESPACE_START

LIBCXXW_NAMESPACE_END

#endif
