<?xml version='1.0'?>

<!--

Copyright 2019 Double Precision, Inc.
See COPYING for distribution information.

Stylesheet for creating includes/x/w/all_appearancesfwd.H from all
appearance/*.xml

-->

<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">

  <xsl:output method="text" />

  <xsl:template match="/root">
    <xsl:text>/* Automatically generated by all_appearancesfwd.xsl */

#ifndef x_w_all_appearancesfwd_H
#define x_w_all_appearancesfwd_H

</xsl:text>

    <xsl:for-each select="appearance">
      <xsl:call-template name="includefwd" />
    </xsl:for-each>
    <xsl:text>
#include &lt;x/w/appearancefwd.H&gt;

#endif
</xsl:text>
  </xsl:template>

  <xsl:template name="includefwd">
    <xsl:text>#include &lt;x/w/</xsl:text>
    <xsl:value-of select="name" />
    <xsl:text>_appearancefwd.H&gt;&#10;</xsl:text>
  </xsl:template>
</xsl:stylesheet>
