/*
** Copyright 2017 Double Precision, Inc.
** See COPYING for distribution information.
*/
#ifndef border_impl_h
#define border_impl_h

#include "border_implfwd.H"
#include "border_implobj.H"
#include <x/ref.H>

LIBCXXW_NAMESPACE_START

//! Base class for \ref border_impl "border implementation objects".

//! Refer to this class as \c LIBCXX_NAMESPACE::w::border_impl_base.

class border_impl_base : public ptrrefBase {

};

LIBCXXW_NAMESPACE_END

#endif
