/*
** Copyright 2017 Double Precision, Inc.
** See COPYING for distribution information.
*/
#ifndef screen_solidcolorpicturesfwd_h
#define screen_solidcolorpicturesfwd_h

#include "x/w/namespace.H"
#include <x/ptrfwd.H>

LIBCXXW_NAMESPACE_START

class screen_solidcolorpicturesObj;

//! A reference to a solid color picture cache.

typedef ref<screen_solidcolorpicturesObj> screen_solidcolorpictures;


LIBCXXW_NAMESPACE_END

#endif
