/*
** Copyright 2017-2019 Double Precision, Inc.
** See COPYING for distribution information.
*/
#ifndef screen_fontcachesfwd_h
#define screen_fontcachesfwd_h

#include "x/w/namespace.H"
#include <x/ptrfwd.H>

LIBCXXW_NAMESPACE_START

class LIBCXX_HIDDEN screen_fontcachesObj;

//! A reference to a cache of fonts.

typedef ref<screen_fontcachesObj> screen_fontcaches;

LIBCXXW_NAMESPACE_END

#endif
