/*
** Copyright 2017-2021 Double Precision, Inc.
** See COPYING for distribution information.
*/
#ifndef screen_picturecachefwd_h
#define screen_picturecachefwd_h

#include "x/w/namespace.H"
#include <x/ptrfwd.H>

LIBCXXW_NAMESPACE_START

class LIBCXX_HIDDEN screen_picturecacheObj;

//! A reference to a screen's picture cache.

typedef ref<screen_picturecacheObj> screen_picturecache;


LIBCXXW_NAMESPACE_END

#endif
