/*
** Copyright 2017-2019 Double Precision, Inc.
** See COPYING for distribution information.
*/
#ifndef current_selectionfwd_H
#define current_selectionfwd_H

#include <x/ptrfwd.H>

#include "x/w/namespace.H"

LIBCXXW_NAMESPACE_START

class LIBCXX_HIDDEN current_selectionObj;

typedef ref<current_selectionObj> current_selection;
typedef ptr<current_selectionObj> current_selectionptr;

LIBCXXW_NAMESPACE_END

#endif
