/*
** Copyright 2018-2020 Double Precision, Inc.
** See COPYING for distribution information.
*/
#ifndef x_w_current_selection_paste_handler_h
#define x_w_current_selection_paste_handler_h

#include "selection/current_selection_paste_handlerfwd.H"
#include "selection/current_selection_paste_handlerobj.H"
#include "selection/current_selection_handler.H"
#include <x/ref.H>

LIBCXXW_NAMESPACE_START

LIBCXXW_NAMESPACE_END

#endif
