/*
** Copyright 2018-2020 Double Precision, Inc.
** See COPYING for distribution information.
*/
#ifndef x_w_itembutton_h
#define x_w_itembutton_h

#include "itemlayoutmanager/itembuttonfwd.H"
#include "itemlayoutmanager/itembuttonobj.H"
#include "x/w/itemlayoutmanagerfwd.H"

#include <x/functionalrefptr.H>
#include <x/ref.H>
#include <vector>

LIBCXXW_NAMESPACE_START

LIBCXXW_NAMESPACE_END

#endif
