/*
** Copyright 2017-2021 Double Precision, Inc.
** See COPYING for distribution information.
*/
#ifndef x_w_bookpagefactory_h
#define x_w_bookpagefactory_h

#include <x/w/bookpagefactoryfwd.H>
#include <x/w/bookpagefactoryobj.H>
#include <x/ref.H>
#include <x/optional_args.H>
#include <x/w/label.H>
#include <x/w/shortcut.H>
#include <x/w/text_param.H>

LIBCXXW_NAMESPACE_START

LIBCXXW_NAMESPACE_END

#endif
