/*
** Copyright 2017 Double Precision, Inc.
** See COPYING for distribution information.
*/
#ifndef x_w_generic_window_h
#define x_w_generic_window_h

#include <x/w/generic_windowfwd.H>
#include <x/w/generic_windowobj.H>
#include <x/ref.H>

LIBCXXW_NAMESPACE_START

//! Base class for \ref generic_window "generic window"s.

//! Refer to this class as \c INSERT_LIBX_NAMESPACE::w::generic_window::base

class generic_windowBase : public ptrrefBase {
};

LIBCXXW_NAMESPACE_END

#endif
