/*
** Copyright 2017-2021 Double Precision, Inc.
** See COPYING for distribution information.
*/
#ifndef x_w_menubarlayoutmanager_h
#define x_w_menubarlayoutmanager_h

#include <x/w/menubarlayoutmanagerfwd.H>
#include <x/w/menubarlayoutmanagerobj.H>
#include <x/w/grid_map_infofwd.H>
#include <x/w/factory.H>
#include <x/w/menu.H>
#include <x/ref.H>

LIBCXXW_NAMESPACE_START

LIBCXXW_NAMESPACE_END

#endif
