/*
** Copyright 2017-2021 Double Precision, Inc.
** See COPYING for distribution information.
*/
#ifndef x_w_namespace_h
#define x_w_namespace_h

#include <x/namespace.h>

#define LIBCXXW_NAMESPACE LIBCXX_NAMESPACE::w

#define LIBCXXW_NAMESPACE_START namespace LIBCXX_NAMESPACE { namespace w {

#define LIBCXXW_NAMESPACE_END } }

namespace x {

	//! LibCXXW library namespace.

	namespace w {

	}
}

#endif
