/*
** Copyright 2017 Double Precision, Inc.
** See COPYING for distribution information.
*/
#ifndef x_w_textlistlayoutstyle_implfwd_h
#define x_w_textlistlayoutstyle_implfwd_h

#include "x/w/namespace.H"

LIBCXXW_NAMESPACE_START

class LIBCXX_HIDDEN textlistlayout_style_impl;

extern const textlistlayout_style_impl &int_menu_list_style;
extern const textlistlayout_style_impl &int_highlighted_list_style;

LIBCXXW_NAMESPACE_END

#endif
