/*
** Copyright 2017-2020 Double Precision, Inc.
** See COPYING for distribution information.
*/

#ifndef x_w_impl_fonts_current_fontcollection_H
#define x_w_impl_fonts_current_fontcollection_H

#include <x/ref.H>
#include <x/w/impl/fonts/current_fontcollectionfwd.H>
#include <x/w/impl/fonts/current_fontcollectionobj.H>
#include <x/w/impl/fonts/fontcollection.H>

LIBCXXW_NAMESPACE_START

LIBCXXW_NAMESPACE_END

#endif
