/*
** Copyright 2018 Double Precision, Inc.
** See COPYING for distribution information.
*/

#ifndef richtext_alteration_config_H
#define richtext_alteration_config_H

#include "richtext/richtextfwd.H"
#include "richtext/richtext_alteration_configfwd.H"

LIBCXXW_NAMESPACE_START

class LIBCXX_HIDDEN richtext_alteration_config {

public:
	const richtextptr ellipsis;
};

LIBCXXW_NAMESPACE_END

#endif
